/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_interview_jni_FaceDetectJni */

#ifndef _Included_org_interview_jni_FaceDetectJni_detectFace
#define _Included_org_interview_jni_FaceDetectJni_detectFace
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL
Java_org_interview_jni_FaceDetectJni_detectFace
  (JNIEnv *, jclass, jobject, jstring);

JNIEXPORT void JNICALL
Java_org_interview_jni_FaceDetectJni_getFaceRects
  (JNIEnv *, jclass, jobjectArray);
#ifdef __cplusplus
}
#endif
#endif
