/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_org_interview_jni_MakeupJni
#define _Included_org_interview_jni_MakeupJni
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL
Java_org_interview_jni_MakeupJni_init
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL
Java_org_interview_jni_MakeupJni_makeup
  (JNIEnv *, jclass, jobject, jobject, jint);

JNIEXPORT void JNICALL
Java_org_interview_jni_MakeupJni_destroy
  (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
